if("undefined"!=typeof nend_domain&&-1!==nend_domain.indexOf("//s.nend.net"))var nend_domain=void 0;var nend_protocol="https:";
if("undefined"==typeof nend_domain)var nend_basic_domain=nend_protocol+"//www.nend.net",nend_domain=nend_protocol+"//ad2.nend.net",nend_icon_domain=nend_protocol+"//ad4.nend.net",nend_c_domain=nend_protocol+"//c1.nend.net",nend_output_domain=nend_protocol+"//output.nend.net",nend_js_domain=nend_protocol+"//js1.nend.net",nend_di_domain="http://di.nend.net",nend_img_domain=nend_protocol+"//img1.nend.net",nend_native_domain=nend_protocol+"//lonb.nend.net";else if("undefined"==typeof nend_output_domain){var tmp_url_obj=
document.createElement("a");tmp_url_obj.href=nend_domain;var nend_hostname=tmp_url_obj.hostname,nend_domain=nend_protocol+"//"+nend_hostname,nend_icon_domain=nend_protocol+"//"+nend_hostname,nend_c_domain=nend_protocol+"//"+nend_hostname,nend_output_domain=nend_protocol+"//"+nend_hostname,nend_js_domain=nend_protocol+"//"+nend_hostname,nend_di_domain=nend_protocol+"//"+nend_hostname,nend_img_domain=nend_protocol+"//"+nend_hostname,nend_native_domain=nend_protocol+"//"+nend_hostname}
"undefined"==typeof nend_basic_domain&&(nend_img_domain=nend_basic_domain=nend_protocol+"//demo.dev.nend.net");var NEND_DEFAULT_LIMIT=10;
if("undefined"==typeof nendCommon)var nendCommon={nend_overlay_params:{},is_tablet:!1,fixed_overlay_flg:!1,constant:{nend_params_done:"done"},prefix:{nend_ad:"nend_ad_",nend_adspace:"nend_adspace_",nend_adcontainer:"nendAdContainer_",nend_adspace_if:"nend_adspace_if_"},nendInlineBannerLimit:{},adIds:{},adUniqInt:0,siteSpotCnt:{},cb:0,init:function(){try{var a=nend_params instanceof Array?nend_params.shift():nend_params;if("undefined"!=typeof a){var b=a.site+"_"+a.spot,c=nendCommon.fn.generateAdId(b),
d=nendCommon.fn.currentSiteSpotCnt(b);"undefined"!=typeof nend_idfa_raw&&(nend_params.idfa_raw=nend_idfa_raw);"undefined"!=typeof nend_idfa_md5&&(nend_params.idfa=nend_idfa_md5);"undefined"!=typeof nend_gaid&&(nend_params.gaid=nend_gaid);!0==nendDisplayTargetBlankAd(a.spot)?a.target="_blank":window.top!==window.self&&(-1!==navigator.userAgent.search(/Android/)?a.target="_blank":a.target="_top");if("10"==a.type){nendCommon.fn.resetAdIds(b);var e=nendCurrentScripts(a.media,a.site,a.spot);if(e){var f=
nendCommon.prefix.nend_adspace+b,k=0;e.forEach(function(a,c,d){"head"==a.parentNode.tagName.toLowerCase()?k=0:(k++,c=document.createElement("div"),d=nendCommon.fn.generateAdId(b),c.setAttribute("id",d),c.setAttribute("class",f),a.parentNode.insertBefore(c,a))});a.ad_num=k;var g=document.getElementById("nend_acquired_ids_"+b);if(null!==g){var p=g.getAttribute("value");null!==p&&(a.acquired_id=p)}this.request(a)}}else{if("1"==a.type){var m=d+1;if(nendCommon.fn.isIconAdFromNpobj(a)&&1<m)return;if(m>
nendCommon.fn.getInlineBannerLimit(b)){nendCommon.fn.removeAdId(b,c);nendCommon.fn.resetInlineBannerLimit(b);return}m="nend_adspace_"+b;nend_style="undefined"!=typeof a.ad_num&&a.ad_num==parseInt(a.ad_num)?"margin-left:auto;margin-right:auto;margin-top:0px;margin-bottom:0px;padding:0px;line-height:1;text-align:center;font-size:0px;border:none;":"margin-left:auto;margin-right:auto;text-align:center;";n=document.createElement("div");n.setAttribute("class",m);n.setAttribute("style",nend_style);var l=
nendCurrentScript(a.media,a.site,a.spot,d);"undefined"===typeof l&&(c=nendCommon.fn.deprecated.adspaceId(b),l=nendCurrentScript(a.media,a.site,a.spot,0));n.setAttribute("id",c);l&&"head"!=l.parentNode.tagName.toLowerCase()?l.parentNode.insertBefore(n,l):document.write('<div id="'+c+'" style="'+nend_style+'"></div>');this.request(a)}else if("2"==a.type){if(1<d)return;var n=document.getElementById(c);this.is_tablet=nendCommon.check_is_tablet();if("undefined"!=typeof a.sp&&0==a.sp){if(!this.is_tablet)return}else if(this.is_tablet)return;
if(-1!=navigator.userAgent.search(/Android/)){var d=0,m=document.getElementsByTagName("meta"),q=m.length;if(0<q)for(l=0;l<q;l++)if("viewport"==m[l].name){d=1;break}if(0==d){var s=document.createElement("meta");s.name="viewport";s.content="width=device-width, initial-scale=1, maximum-scale=4, minimum-scale=0.3";document.getElementsByTagName("head").item(0).appendChild(s)}}this.fixed_overlay_flg=nendDisplayFixedOverlay(a.spot);nend_style=!0==this.fixed_overlay_flg?"position: fixed; left: 0px; z-index: 9999; bottom: 0px; display: none;":
"position: absolute; left: 0px; z-index: 9999; top: "+(window.scrollY+window.innerHeight)+"px; display: none;";document.write('<div id="'+c+'" style="'+nend_style+'"></div>');this.nend_overlay_params=a;window.addEventListener("DOMContentLoaded",nendOlObject.init,!1);window.addEventListener("DOMContentLoaded",this.load,!1);"undefined"===typeof window.onorientationchange?window.addEventListener("resize",nendOlObject.renew,!1):window.addEventListener("orientationchange",nendOlObject.renew,!1)}"undefined"!=
typeof report_click_url&&""!=report_click_url&&(document.getElementById(c).report_click_url=report_click_url,report_click_url="")}}}catch(r){console.log(r)}},load:function(a){if(nendCommon.is_portrait()||nendCommon.is_tablet)try{var b=document.getElementById("nend_feed_"+nendCommon.nend_overlay_params.site+"_"+nendCommon.nend_overlay_params.spot);"undefined"!=typeof b&&null!==b&&b.parentNode.removeChild(b);nendCommon.request(nendCommon.nend_overlay_params)}catch(c){console.log(c)}},request:function(a){var b=
function(a){try{var b=a.site+"_"+a.spot;"2"==a.type&&(document.getElementById(nendCommon.prefix.nend_adspace+b).style.display="none",a.width=nendDimension.get(nendCommon.is_portrait()).ad_width,a.height=nendDimension.get(nendCommon.is_portrait()).ad_height);var b=[],c,k;for(k in a)c=a[k],"string"==typeof c&&(c=c.replace("#","%23")),b.push(k+"="+c);var g="10"==a.type?nend_native_domain+"/njfeed.php?"+b.join("&"):nendCommon.fn.isIconAdFromNpobj(a)?nend_icon_domain+"/ifeed.php?"+b.join("&"):nend_domain+
"/feed.php?"+b.join("&"),g=g+("&cb="+Math.random().toString().substr(2)+nendCommon.cb++),p=document.createElement("script");p.setAttribute("src",g);p.setAttribute("type","text/javascript");document.getElementsByTagName("body")[0].appendChild(p)}catch(m){console.log(m)}};if("undefined"===typeof navigator.userAgentData)b(a);else try{navigator.userAgentData.getHighEntropyValues(["platform","platformVersion","model"]).then(function(c){"undefined"!==c&&"Android"===c.platform&&(""!==c.model&&(a.n=c.model),
""!==c.platformVersion&&(a.e=c.platformVersion));b(a)})}catch(c){console.log(c),b(a)}},is_portrait:function(){return"undefined"==typeof window.orientation||0==window.orientation%180},check_is_tablet:function(){var a=navigator.userAgent;if(-1!=a.search(/iPhone/)||-1!=a.search(/iPod/))return!1;if(-1!=a.search(/iPad/))return!0;if(-1!=a.search(/Android/)||-1!=a.search(/Tizen/))return-1!=a.search(/Mobile/)?!1:!0},display:function(a){try{var b=a.s+"_"+a.w,c=nendCommon.fn.getAdId(b),d=nendCommon.prefix.nend_adspace+
b,e=nendScripts();nendCommon.siteSpotCnt[b]>e.length&&(c=nendCommon.fn.deprecated.adspaceId(b));var f=document.getElementById(c);2==a.y&&"undefined"!=typeof nendOlObject&&(nendOlObject.kind=a.k);"undefined"==typeof a.v&&(a.v=1);var k=(new Date).getTime(),g="a="+a.a+"&c="+a.c+"&m="+a.m+"&i="+a.i+"&d="+a.d+"&s="+a.s+"&w="+a.w+"&k="+a.k+"&p="+a.p+"&q="+a.q+"&v="+a.v+"&y="+a.y+"&cb="+k+"&art="+a.art;"undefined"!=typeof a.z&&""!=a.z&&"undefined"!=typeof a.u&&""!=a.u?g=g+"&z="+a.z+"&u="+a.u+"&o="+a.o+"&e="+
a.e+"&n="+a.n+"&l="+a.l:("undefined"!==typeof a.e&&""!==a.e&&(g+="&e="+a.e),"undefined"!==typeof a.n&&""!==a.n&&(g+="&n="+a.n));"undefined"!=typeof a.idfa&&(g+="&idfa="+a.idfa);"undefined"!=typeof a.idfa_raw&&(g+="&idfa_raw="+a.idfa_raw);"undefined"!=typeof a.gaid&&(g+="&gaid="+a.gaid);var p;if(p=f.report_click_url)g=g+"&rc="+encodeURIComponent(p);if(1==a.y&&!0==nendDisplayNewAd(a.d)){var m=document.createElement("img");m.setAttribute("src",nend_output_domain+"/image_output.php?"+g);m.setAttribute("style",
"margin:0px !important;padding:0px !important;border:none !important;width:"+a.p+"px; height:"+a.q+"px;font-size: 0px !important;text-indent: 0px !important;");var l=document.createElement("a");l.setAttribute("href",nend_c_domain+"/click.php?"+g);l.setAttribute("style","margin:0px !important;padding:0px !important;border:none !important;font-size: 0px !important;");"undefined"==typeof a.g?l.setAttribute("target","_blank"):"undefined"!=typeof a.g&&""!=a.g&&l.setAttribute("target",a.g);l.appendChild(m);
if("undefined"==typeof a.bc||"undefined"!=typeof a.bc&&0==(221198&a.bc)){var n=document.createElement("div");n.setAttribute("class","info_elem");n.setAttribute("style","margin:0px !important;padding:0px !important;border:none !important;position: absolute !important;top: 0px !important;width: 77px !important;height: 15px !important;z-index: 8888 !important;background-color:transparent !important;right: -58px;-webkit-transition: all 0.15s ease-out;-ms-transition: all 0.15s ease-out;-o-transition: all 0.15s ease-out;-moz-transition: all 0.15s ease-out;transition: all 0.15s ease-out;-webkit-tap-highlight-color: rgba(0,0,0,0);");
var q=document.createElement("div");q.setAttribute("style","margin:0px !important;padding:0px !important;border:none !important;position: absolute !important;top: 0px !important;width: 77px !important;height: 15px !important;background-repeat: no-repeat !important;background-size: contain !important;background-image: url("+nend_img_domain+"/img/info/nend_i.png) !important;background-color:transparent !important;");var s=document.createElement("a");s.setAttribute("style","margin:0px !important;padding:0px 0px 0px 18px !important;border:none !important;position: absolute !important;top: 0px !important;width: 77px !important;height: 15px !important;display: none;background-color:transparent !important;");
s.setAttribute("href",nend_basic_domain+"/privacy/explainoptout?spot="+a.w);s.setAttribute("target","_blank");n.appendChild(q);n.appendChild(s)}var r=document.createElement("div");r.setAttribute("class","nendAdContainer");r.setAttribute("style","margin:0px !important;padding:0px !important;border:none !important;display:inline-block !important; overflow: hidden !important;font-size: 0px !important;text-indent: 0px !important;position: relative !important;");r.appendChild(l);if("undefined"==typeof a.bc||
"undefined"!=typeof a.bc&&0==a.bc)r.appendChild(n),n.addEventListener("click",function(){nendCommon.infoAnimate(n,s);setTimeout(function(){nendCommon.infoReset(n,s)},2500)},!1);f.innerHTML="";f.setAttribute("style","margin-left:auto;margin-right:auto;text-align:center;line-height:0;");f.appendChild(r);l.addEventListener("click",nendCommon.beforeTransition,!1);if("undefined"!=typeof a.view_size&&2==a.view_size&&!1===nendCommon.check_is_tablet()){"undefined"===typeof window.onorientationchange?window.addEventListener("resize",
nendOlObject.callChangeFullWidthStyleForRotate,!1):window.addEventListener("orientationchange",nendOlObject.callChangeFullWidthStyleForRotate,!1);window.addEventListener("touchend",nendOlObject.changeFullWidthStyle,!1);m.setAttribute("data-width",a.p);m.setAttribute("data-height",a.q);var t=window.innerWidth/a.p,h="#"+c+" .nendAdContainer.nend_adcontainer_fullwidth_portrait { margin:0px !important;padding:0px !important;border:none !important;display:inline-block !important; overflow: hidden !important;font-size: 0px !important;text-indent: 0px !important;position: absolute !important;left: 0px !important; width :"+
window.innerWidth+"px !important; height: "+a.q*t+"px;}",e="#"+c+" .nendAdContainer.nend_adcontainer_fullwidth_landscape { margin:0px !important;padding:0px !important;border:none !important;display:inline-block !important; overflow: hidden !important;font-size: 0px !important;text-indent: 0px !important;position: relative !important; }",u="#"+c+".nend_adspace_fullwidth_portrait { margin-left:auto;margin-right:auto;text-align:center;line-height:0;height: "+a.q*t+"px; }",c="#"+c+".nend_adspace_fullwidth_landscape { margin-left:auto;margin-right:auto;text-align:center;line-height:0; }",
w=document.createElement("style");document.head.appendChild(w);var v=w.sheet;v.insertRule(h,0);v.insertRule(e,0);v.insertRule(u,0);v.insertRule(c,0);!0===nendCommon.is_portrait()?(add_class_name="portrait",m.setAttribute("style","width:"+window.innerWidth+"px !important; height: "+a.q*t+"px !important;")):add_class_name="landscape";r.classList.add("nend_adcontainer_fullwidth_"+add_class_name);f.classList.add("nend_adspace_fullwidth_"+add_class_name,"nend_adspace_fullwidth");r.setAttribute("style",
"");f.setAttribute("style","")}nendCommon.fn.resetInlineBannerLimit(b)}else m=document.createElement("img"),m.setAttribute("src",nend_output_domain+"/image_output.php?"+g),m.setAttribute("border",0),m.setAttribute("style","width:"+a.p+"px; height:"+a.q+"px;"),2==a.y&&m.setAttribute("id","nend_banner_img"),l=document.createElement("a"),l.setAttribute("href",nend_c_domain+"/click.php?"+g),"undefined"==typeof a.g?l.setAttribute("target","_blank"):"undefined"!=typeof a.g&&""!=a.g&&l.setAttribute("target",
a.g),l.appendChild(m),f.innerHTML="",f.appendChild(l),l.addEventListener("click",nendCommon.beforeTransition,!1);2==a.y&&"undefined"!=typeof nendOlObject&&(nendDimension.vertical_width=a.p,nendDimension.vertical_height=a.q,nendCommon.is_tablet&&(nendDimension.horizontal_width=a.p,nendDimension.horizontal_height=a.q),nendOlObject.touchstart(),nendOlObject.touchend());if(1==a.y&&f.id===d){var x=f.children[0];x.className.match(/nendAdContainer$|nendAdContainer /)&&nendCommon.fn.addId(x,nendCommon.prefix.nend_adcontainer+
b)}}catch(y){console.log(y)}},nativeDisplay:function(a){try{var b=a.site+"_"+a.spot,c=document.createElement("img");c.setAttribute("style","border:none !important;width:0px !important;height:0px !important;padding:0px !important;margin:0px !important; display:none !important;");var d=(new Date).getTime();c.setAttribute("src",a.impression_count_url+"&cb="+d);c.setAttribute("alt","nend_impression_count_url");document.body.appendChild(c);var c="nend_acquired_ids_"+b,e=document.getElementById(c);null==
e&&(e=document.createElement("input"),e.setAttribute("type","hidden"),e.setAttribute("id",c),document.body.appendChild(e));e.setAttribute("value",a.acquired_ids);var f=nendCommon.prefix.nend_adspace+b,k=document.getElementsByClassName(f),g=a.default_ads.length,p=0;for(Array.prototype.forEach.call(k,function(){if(!(g<p+1)){var c=nendCommon.fn.getAdId(b),c=document.getElementById(c),d=c.parentNode,e=document.createElement("span");e.innerHTML=a.default_ads[p].elem.trim();e=e.childNodes;p++;for(var f=
0,k=e.length;f<k;f++)"object"==typeof e[f]&&d.insertBefore(e[f],c)}});(k=document.getElementsByClassName(f))&&k.length;)k[0].parentNode.removeChild(k[0]);var m=nendCurrentScripts(a.media,a.site,a.spot);m&&m.forEach(function(a,b,c){a.textContent=""})}catch(l){console.log(l)}},infoAnimate:function(a,b){b.style.display="block";a.style.right="0px"},infoReset:function(a,b){b.style.display="none";a.style.right="-58px"},iconDisplay:function(a){try{var b=a.site+"_"+a.spot,c=nendCommon.adIds[b].shift(),d=
document.getElementById(c),e,f;"undefined"!=typeof a.width&&a.width==parseInt(a.width)&&"undefined"!=typeof a.height&&a.height==parseInt(a.height)?(e=parseInt(a.width),f=parseInt(a.height)):f=e=57;e>f?f=e:f>e&&(e=f);var k;k="undefined"!=typeof a.align&&2==a.align?"right":"undefined"!=typeof a.align&&3==a.align?"left":"center";var g=parseInt(a.default_ads.length);Math.round(310/g)-2<e&&(e=Math.round(310/g)-2,f=Math.round(310/g)-2);var p;"center"==k?(p=(Math.round(310/g)-e)/2,1>p&&(p=1)):(p=Math.round(0.145*
e),p>Math.round((310-g*e)/(2*g))&&(p=Math.round((310-g*e)/(2*g))));var m=Math.round(0.169*e);7>parseInt(m)&&(m=7);var l;l="undefined"==typeof a.text_color?"#000000":a.text_color;var n;n="undefined"!=typeof a.target&&""!=a.target?a.target:"_blank";var q=document.createElement("ul");q.setAttribute("id","nend_icon_list_"+b);q.setAttribute("style","text-align:"+k+";text-indent:0;padding:0px;margin:0px;line-height:1;font-size:0px;border:none;background:transparent;");c={};k={};for(var g={},s={},r={},t=
{},h=0;h<a.default_ads.length;h++){c[h]=document.createElement("li");c[h].setAttribute("id","nend_icon_"+b+"_"+h);c[h].setAttribute("style","display:inline-block;padding:0px;margin:0px;line-height:1;border:none;background:transparent;text-indent:0;font-size:0px;vertical-align:top;");k[h]=document.createElement("a");k[h].setAttribute("href",a.default_ads[h].click_url);k[h].setAttribute("target",n);k[h].setAttribute("style","text-decoration:none;background:transparent;border:none;padding:0px;margin:0px;font-size:0px;line-height:1;");
k[h].addEventListener("click",nendCommon.beforeTransitionIcon,!1);g[h]=document.createElement("img");g[h].setAttribute("src",a.default_ads[h].image_url);g[h].setAttribute("border",0);g[h].setAttribute("alt",a.default_ads[h].icon_text);"undefined"==typeof a.space||1==a.space?g[h].setAttribute("style","border:none;float:none;background:transparent;width:"+e+"px;height:"+f+"px;padding:0px;margin-top:1px;margin-bottom:1px;margin-right:"+p+"px;margin-left:"+p+"px;"):g[h].setAttribute("style","border:none;float:none;background:transparent;width:"+
e+"px;height:"+f+"px;padding:0px;margin:1px;");k[h].appendChild(g[h]);if("undefined"==typeof a.text_display||1==a.text_display)s[h]=document.createElement("br"),s[h].setAttribute("style","line-height:1;font-size:0px;"),r[h]=document.createElement("span"),r[h].setAttribute("id","nend_icon_title_"+b+"_"+h),"undefined"!=typeof a.space&&1==a.space?r[h].setAttribute("style","display:block;float:none;margin-top:4px;margin-bottom:2px;margin-left:auto;margin-right:auto;padding:0px;width:"+(e+2*p)+"px;border:none;line-height:1;text-align:center;text-indent:0;font-style:normal;font-weight:normal;letter-spacing:0px;font-size:"+
m+"px;color:"+l+";background:transparent;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"):r[h].setAttribute("style","display:block;float:none;margin-top:4px;margin-bottom:2px;margin-left:auto;margin-right:auto;padding:0px;width:"+e+"px;border:none;line-height:1;text-align:center;text-indent:0;font-style:normal;font-weight:normal;letter-spacing:0px;font-size:"+m+"px;color:"+l+";background:transparent;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"),t[h]=document.createTextNode(a.default_ads[h].icon_text),
r[h].appendChild(t[h]),k[h].appendChild(s[h]),k[h].appendChild(r[h]);c[h].appendChild(k[h]);q.appendChild(c[h])}var u=document.createElement("img");u.setAttribute("style","border:none !important;width:0px !important;height:0px !important;padding:0px !important;margin:0px !important; display:none !important;");var w=(new Date).getTime();u.setAttribute("src",a.impression_count_url+"&cb="+w);u.setAttribute("alt","");d.innerHTML="";d.appendChild(q);d.appendChild(u)}catch(v){console.log(v)}},addTag:function(a){try{var b=
a.s+"_"+a.w,c,d=!1;"if"in a&&(d=!0);var e=nendDimension.get(!0),f={width:e.ad_width,height:e.ad_height},k={width:e.ad_width,height:e.ad_height,threedad:!1};"threedad"in a&&(k.threedad=a.threedad);"iw"in a&&(k.width=a.iw,f.width=a.iw);"ih"in a&&(k.height=a.ih,f.height=a.ih);"dw"in a&&(f.width=a.dw);"dh"in a&&(f.height=a.dh);var g=nendCommon.fn.getAdId(b),p=document.getElementById(g);p.innerHTML="";p.style.textAlign="center";if(d){var m=g.replace(nendCommon.prefix.nend_adspace,nendCommon.prefix.nend_adspace_if);
"fif"in a&&a.fif?nendCommon.fn.generateFif(a.ta,g,m,f,k):nendCommon.fn.generateIframe(a.ta,g,m,k)}else{var l=document.createElement("div");l.innerHTML=a.ta;tagNodes=l.childNodes;tagNodeLength=tagNodes.length;var n;for(n=0;n<tagNodeLength;n++)if("undefined"!=typeof tagNodes[n].tagName)if("script"==tagNodes[n].tagName.toLowerCase()){var q=document.createElement("script");q.setAttribute("type","text/javascript");null!=tagNodes[n].getAttribute("charset")&&q.setAttribute("charset",tagNodes[n].getAttribute("charset"));
null!=tagNodes[n].getAttribute("data-gsmuserblock")&&(q.setAttribute("data-gsmuserblock",tagNodes[n].getAttribute("data-gsmuserblock")),c=!0);null!=tagNodes[n].getAttribute("src")?q.setAttribute("src",tagNodes[n].getAttribute("src")):q.innerHTML=tagNodes[n].innerHTML;c?document.body.appendChild(q):p.appendChild(q)}else{var s=tagNodes[n].cloneNode(!0);p.appendChild(s)}}2==a.y&&(nendDimension.vertical_width=f.width,nendDimension.vertical_height=f.height,nendDimension.horizontal_width=f.width,nendDimension.horizontal_height=
f.height,nendOlObject.kind=a.k,nendOlObject.s=a.s,nendOlObject.w=a.w,nendOlObject.ifr=d,nendOlObject.touchstart(),nendOlObject.touchend(),window.removeEventListener("resize",this.load,!1))}catch(r){console.log(r)}},beforeTransition:function(a){var b;(b=this.parentNode.report_click_url)&&nendCommon.requestClickUrl(b)},beforeTransitionIcon:function(a){},requestClickUrl:function(a){var b=new XMLHttpRequest;b.open("GET",a,!0);b.send(null)},pingClickUrl:function(a){var b="cb="+(new Date).getTime();a=a.replace(/(&cb=\d+)/,
"&"+b);b=document.createElement("img");b.setAttribute("src",a);b.setAttribute("border",0);b.setAttribute("style","width:0; height:0; margin:0; padding:0;");document.getElementById(nendCommon.prefix.nend_adspace+nend_params.site+"_"+nend_params.spot).appendChild(b)},pingImpressionUrl:function(a){nendCommon.pingClickUrl(a)},fn:{generateAdId:function(a){var b="";"undefined"===typeof nendCommon.adIds[a]?(nendCommon.adIds[a]=[],b=nendCommon.fn.deprecated.adspaceId(a)):(b=nendCommon.fn.currentAdUniqInt(),
b=nendCommon.fn.createId(b));nendCommon.adIds[a].push(b);return b},getAdId:function(a){return nendCommon.adIds[a].shift()},removeAdId:function(a,b){nendCommon.adIds[a]=nendCommon.adIds[a].filter(function(a){return a!==b})},countAdIds:function(a){return nendCommon.adIds[a].length},resetAdIds:function(a){nendCommon.adIds[a]=[]},createId:function(a){return nendCommon.prefix.nend_ad+a},currentAdUniqInt:function(){return nendCommon.adUniqInt++},getInlineBannerLimit:function(a){"undefined"===typeof nendCommon.nendInlineBannerLimit[a]&&
(nendCommon.nendInlineBannerLimit[a]=NEND_DEFAULT_LIMIT);return nendCommon.nendInlineBannerLimit[a]},resetInlineBannerLimit:function(a){0===nendCommon.fn.countAdIds(a)&&(nendCommon.nendInlineBannerLimit[a]=nendCommon.fn.currentAdUniqInt(!1)+1+NEND_DEFAULT_LIMIT)},currentSiteSpotCnt:function(a){"undefined"===typeof nendCommon.siteSpotCnt[a]?nendCommon.siteSpotCnt[a]=0:nendCommon.siteSpotCnt[a]++;return nendCommon.siteSpotCnt[a]},addId:function(a,b){"undefined"===typeof a.id||""==a.id?a.setAttribute("id",
b):a.setAttribute("id",a.id+" "+b)},isIconAdFromNpobj:function(a){return"undefined"!=typeof a.ad_num&&a.ad_num==parseInt(a.ad_num)},deprecated:{adspaceId:function(a){return nendCommon.prefix.nend_adspace+a}},generateIframe:function(a,b,c,d){b=document.getElementById(b);var e=document.createElement("iframe");e.id=c;e.scrolling="no";e.style.borderStyle="solid";e.style.borderWidth="0";e.style.width=d.width+"px";e.style.height=d.height+"px";b.appendChild(e);c=e.contentWindow.document;c.open();c.writeln("<html>");
c.writeln("<head><style>body,div,img{margin:0;padding:0;}</style></head>");c.writeln("<body>");c.writeln(a);c.writeln("</body>");c.writeln("</html>");c.close()},generateFif:function(a,b,c,d,e){b=document.getElementById(b);b.style.width=d.width+"px";b.style.height=d.height+"px";d=document.createElement("iframe");d.id=c;d.src="javascript:false";d.scrolling="no";d.style.backgroundColor="transparent";d.style.borderStyle="solid";d.style.borderWidth="0";d.style.width=e.width+"px";d.style.height=e.height+
"px";d.style.marginLeft="auto";d.style.marginRight="auto";d.style.textAlign="center";b.appendChild(d);d=d.contentWindow.document;d.open();d.writeln("<html>");d.writeln("<head><style>body,div,img{margin:0;padding:0;}</style></head>");d.writeln("<body>");d.writeln("<script>");d.writeln("inDapIF = true;");d.writeln("\x3c/script>");d.writeln(a);d.writeln("</body>");d.writeln("</html>");d.close();nendCommon.fn.isInFif()&&e.threedad&&(a=nendCommon.fn.findSspFif(c),null!==a&&nendCommon.fn.shape3dadForSspFif(a,
e.height))},isInFif:function(){return window.inDapIF?!0:window!==window.parent},findSspFif:function(a){for(var b=null,c=window.parent.document.getElementsByTagName("iframe"),d=0;d<c.length;d++){var e=c[d];if(null!==e.contentWindow.document.getElementById(a)){b=e;break}}return b},shape3dadForSspFif:function(a,b){parseInt(nendCommon.fn.css(a,"height"))>=b||(a.style.backgroundColor="transparent",a.style.height=b+"px")},css:function(a,b){return a.ownerDocument.defaultView.getComputedStyle(a)[b]}}};
if("undefined"==typeof nendDimension)var nendDimension={vertical_width:320,vertical_height:50,horizontal_width:480,horizontal_height:32,get:function(a){return{ad_width:a?nendDimension.vertical_width:nendDimension.horizontal_width,ad_height:a?nendDimension.vertical_height:nendDimension.horizontal_height}},magnify:function(a,b){var c={};basic_dims=this.get(a);for(var d in basic_dims)c[d]=basic_dims[d]*b;return c}};
if("undefined"==typeof nendOlObject)var nendOlObject={actual_screen_width:nendDimension.get(!0).ad_width,actual_ad_height:nendDimension.get(!0).ad_height,show_timer_msec:!1==nendCommon.fixed_overlay_flg?1E3:0,slide_dir:1,slide_interval:10,init:function(a){nendOlObject.target=document.getElementById(nendCommon.prefix.nend_adspace+nendCommon.nend_overlay_params.site+"_"+nendCommon.nend_overlay_params.spot);nendOlObject.target.addEventListener("touchstart",nendOlObject.stop_propagation,!1);document.addEventListener("touchstart",
nendOlObject.touchstart,!1);document.addEventListener("touchend",nendOlObject.touchend,!1);document.addEventListener("scroll",nendOlObject.touchend,!1)},touchstart:function(a){!1!=nendCommon.fixed_overlay_flg&&nendCommon.is_portrait()||nendOlObject.hide();clearInterval(nendOlObject.move_timer);clearTimeout(nendOlObject.timer)},touchend:function(a){clearTimeout(nendOlObject.timer);if(nendCommon.is_portrait()||nendCommon.is_tablet)nendOlObject.timer=setTimeout(function(){if(3!=nendOlObject.kind||3==
nendOlObject.kind&&1<=nendOlObject.get_zoom_ratio())nendOlObject.redraw(),!1==nendCommon.fixed_overlay_flg&&nendOlObject.move()},nendOlObject.show_timer_msec)},renew:function(a){if(2==nendCommon.nend_overlay_params.type)try{var b=document.getElementById("nend_feed_"+nendCommon.nend_overlay_params.site+"_"+nendCommon.nend_overlay_params.spot);if("undefined"==typeof b||null===b){nendCommon.request(nendCommon.nend_overlay_params);return}}catch(c){console.log(c)}nendOlObject.touchstart();nendOlObject.touchend()},
redraw:function(){var a=nendCommon.is_portrait(),b=nendOlObject.get_zoom_ratio(),c=nendDimension.magnify(a,b);nendOlObject.actual_screen_width=c.ad_width;nendOlObject.actual_ad_height=3==nendOlObject.kind&&1<b?nendDimension.magnify(a,1).ad_height:c.ad_height;c=Math.max(document.body.clientHeight,document.documentElement.clientHeight,document.body.scrollHeight,document.documentElement.scrollHeight);b=!1;nendDisplayLowerOverlay(nendCommon.nend_overlay_params.spot)?b=!1:window.innerHeight-document.body.offsetHeight>
nendOlObject.actual_ad_height?b=!1:window.scrollY<nendOlObject.actual_ad_height?b=!1:c-window.scrollY-window.innerHeight<nendOlObject.actual_ad_height&&(b=!0);c=0;!1==nendCommon.fixed_overlay_flg&&(c=window.scrollY+1);!0===b?(!1==nendCommon.fixed_overlay_flg&&(c-=nendOlObject.actual_ad_height),nendOlObject.slide_dir=-1):(c+=window.innerHeight,nendOlObject.slide_dir=1);var d=nendOlObject.target;!1==nendCommon.fixed_overlay_flg||!0===b?d.style.top=c+"px":(d.style.top="auto",d.style.bottom="0px");d.style.left=
!1==nendCommon.fixed_overlay_flg?window.scrollX+"px":"0px";d.style.width=nendOlObject.actual_screen_width+"px";d.style.height=nendOlObject.actual_ad_height+"px";d.style.opacity="1.0";d.style.visibility="visible";1==nendOlObject.kind||2==nendOlObject.kind?(a=document.getElementById("nend_banner_img"),a.style.width=nendOlObject.actual_screen_width+"px",a.style.height=nendOlObject.actual_ad_height+"px"):3==nendOlObject.kind&&nendOlObject.ifr&&(b=document.getElementById("nend_adspace_if_"+nendOlObject.s+
"_"+nendOlObject.w),b.style.width=nendDimension.get(a).ad_width+"px",b.style.height=nendDimension.get(a).ad_height+"px",b.style.textAlign="center");!0==nendCommon.fixed_overlay_flg&&(nendOlObject.target.style.display="block")},move:function(){nendOlObject.target.style.display="block";nendOlObject.move_start_time=(new Date).getTime();nendOlObject.move_start_position=parseInt(nendOlObject.target.style.top.replace(/px/,""));clearInterval(nendOlObject.move_timer);nendOlObject.move_timer=setInterval(nendOlObject.animate,
nendOlObject.slide_interval)},animate:function(){var a=nendOlObject.timeprofile(nendOlObject.move_start_time,(new Date).getTime());nendOlObject.target.style.top=nendOlObject.move_start_position-nendOlObject.slide_dir*a+"px"},timeprofile:function(a,b){var c=nendOlObject.quickappear(b-a);return!1===c?(clearInterval(nendOlObject.move_timer),nendOlObject.hide(),0):c},quickappear:function(a){var b=36E5;"number"==typeof nend_params.staytime&&(b=1E3*nend_params.staytime);return 0>a?nendOlObject.actual_ad_height*
(1-Math.pow(a-0,2)/Math.pow(0,2)):a<0+b?nendOlObject.actual_ad_height:a<0+b+500?nendOlObject.actual_ad_height*(1-Math.pow(a-0-b,2)/Math.pow(500,2)):!1},hide:function(){nendOlObject.target.style.display="none"},stop_propagation:function(a){a.stopPropagation()},get_zoom_ratio:function(){return window.innerWidth/nendDimension.get(nendCommon.is_portrait()).ad_width},callChangeFullWidthStyleForRotate:function(){var a=0;-1!=navigator.userAgent.search(/Android/)&&(a=300);setTimeout(function(){nendOlObject.changeFullWidthStyle()},
a)},changeFullWidthStyle:function(){var a=nendCommon.prefix.nend_adspace,b="",c="",d=b="",e=nendCommon.is_portrait(),f=document.getElementsByClassName("nend_adspace_fullwidth");for(i=0;i<f.length;i++)b=f[i].id.substring(a.length),document.getElementById("img_"+b)&&document.getElementById("nendAdContainer_"+b)&&(c=document.getElementById("img_"+b),b=document.getElementById("nendAdContainer_"+b),e?(d=window.innerWidth/c.getAttribute("data-width")*c.getAttribute("data-height"),c.setAttribute("style",
"width:"+window.innerWidth+"px !important; height:"+d+"px !important; position: absolute !important; left: 0px;"),f[i].setAttribute("style","height:"+d+"px !important;"),b.setAttribute("style","width:"+window.innerWidth+"px !important; height:"+d+"px !important; position: absolute !important; left: 0px;")):(c.setAttribute("style","width:"+c.getAttribute("data-width")+"px !important; height:"+c.getAttribute("data-height")+"px !important; position: relative !important;"),f[i].setAttribute("style","width:"+
c.getAttribute("data-width")+"px !important; height:"+c.getAttribute("data-height")+"px !important;"),b.setAttribute("style","width:"+c.getAttribute("data-width")+"px !important; height:"+c.getAttribute("data-height")+"px !important; position: relative !important;")))}};function nendDisplay(a){nendCommon.display(a)}function nendNativeDisplay(a){nendCommon.nativeDisplay(a)}function nendIconDisplay(a){nendCommon.iconDisplay(a)}function nendAddTag(a){nendCommon.addTag(a)}
function nendDisplayNewAd(a){for(var b=[5547,9140],c=0;c<b.length;c++)if(b[c]==a)return!1;return!0}function nendDisplayTargetBlankAd(a){for(var b=[443959,443961,443964,443968,443970,443973,443977,443979],c=0;c<b.length;c++)if(b[c]==a)return!0;return!1}function nendDisplayLowerOverlay(a){for(var b=[22533,523864,523872,523867,497607,497609,523875,523874,497611,497610,514020,607829],c=0;c<b.length;c++)if(b[c]==a)return!0;return!1}
function nendDisplayFixedOverlay(a){return 0<=navigator.userAgent.indexOf("Android")&&2.3<parseFloat(navigator.userAgent.slice(navigator.userAgent.indexOf("Android")+8))||navigator.userAgent.match(/(iPhone|iPad|iPod)/)&&(a=navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/),5<=parseInt(a[1],10))?!0:!1}function nendScripts(){return Array.prototype.slice.call(document.scripts).filter(function(a){return 0<(a.innerText?a.innerText:a.textContent).indexOf("nend_params")})}
function nendMatchParamScripts(a,b,c,d){return a.filter(function(a){a=((a.innerText?a.innerText:a.textContent).match(/.*?var +?nend_params *?=(.*)?;/)||[])[1];if(!a)return!1;var f=null;try{return f=JSON.parse(a),f.media==b&&f.site==c&&f.spot==d}catch(k){}try{return f=eval("("+a+")"),f.media==b&&f.site==c&&f.spot==d}catch(g){}return!1})}function nendCurrentScript(a,b,c,d){return nendMatchParamScripts(nendScripts(),a,b,c)[d]}
function nendCurrentScripts(a,b,c){var d=nendScripts();if(1>d.length)return!1;a=nendMatchParamScripts(d,a,b,c);return 1>a.length?!1:a}var nend_user_agent=navigator.userAgent;!navigator.cookieEnabled||-1==nend_user_agent.search(/Android/)&&-1==nend_user_agent.search(/iPhone/)&&-1==nend_user_agent.search(/iPod/)&&-1==nend_user_agent.search(/iPad/)&&-1==nend_user_agent.search(/Tizen/)?!1==navigator.cookieEnabled&&(window.top!==window.self&&-1!=nend_user_agent.search(/Android/))&&nendCommon.init():nendCommon.init();
